### ISSUE TITLE
[Bug] Nmread does not work

### ISSUE THREAD

**Issue by Aonodensetsu** [miversen33/netman.nvim#204] opened 2024-03-14 17:38 UTC
When using the netman GUI integrated into neo-tree, remote files can be opened. When using Nmread however (and netman:read), they do not open.

Log: https://h.00t.in/m/netman.log

I'm the person on Debian, running the v1.15 branch.

**Comment by Aonodensetsu** [comment] 2024-03-14 17:45
I'm working on fully lazy-loading neo-tree, which is why I found this to be a thing.
![image](https://github.com/miversen33/netman.nvim/assets/58662350/a8ce8d02-0676-4b69-8168-f9dd483335c0)

**Comment by miversen33** [comment] 2024-03-14 23:21
Ahh ya looks like you got bit with the shitty documentation bug :) Try switching out 
```lua
vim.defer_fn(function() require'netman':read(f) end, 0)
```

with 
```lua
vim.defer_fn(function() require'netman'.read(f) end, 0)
```

It looks like the documentation still refers to using `:` instead of `.` when making function calls. That is bad and wrong. Lemme know if that works :)

**Comment by Aonodensetsu** [comment] 2024-03-15 12:53
cool, but as I said the same applies to `:Nmread`, so that does not fix my issue

they seem to work under specific circumstances:
- the second or later time `Nmread` or `.read` is executed
- for files

the file list does not open for folders, and trying to do as i'm doing even with defer, does not work

**Comment by Aonodensetsu** [comment] 2024-03-15 13:02
As we discussed in my previous ticket, I can't move to main because it crashes neovim on load.

**Comment by miversen33** [comment] 2024-03-15 13:24
Are you saying that my [proposed fix](https://github.com/miversen33/netman.nvim/issues/174#issuecomment-1867081237) didn't work? I asked if it did and didn't hear anything back so I assumed it did. Getting you on main is important

**Comment by Aonodensetsu** [comment] 2024-03-15 13:30
the v1.15 branch as well as [commenting the line](https://github.com/miversen33/netman.nvim/issues/174#issuecomment-1865618044) worked, i didn't get to the testing branch before it was 404, but assumed it was the same fix

**Comment by Aonodensetsu** [comment] 2024-03-15 13:34
i think nvim cached the main branch from before the fix as a clean install off main now works

**Comment by miversen33** [comment] 2024-03-15 13:41
Perfect :) I don't assume getting you on `main` fixed this issue though, correct?

**Comment by Aonodensetsu** [comment] 2024-03-15 13:50
no, still on the second attempt
it also seems to not set the filetype

**Comment by Aonodensetsu** [comment] 2024-03-15 13:53
the 'fetching file' alert shows up every time, even if it doesn't actually open the file

**Comment by miversen33** [comment] 2024-03-15 13:54
`:e` most certainly should be working, at least on a file level :(

Can you (for the sake of my sanity) show me an `:e` command that doesn't work?

**Comment by Aonodensetsu** [comment] 2024-03-15 13:56
`:e scp://self/.bashrc`
before
![image](https://github.com/miversen33/netman.nvim/assets/58662350/8a618cbd-8288-4e44-aef1-95abe2bb5779)
after
![image](https://github.com/miversen33/netman.nvim/assets/58662350/ad1fbc45-7ff4-4a68-a62f-72e8c2cef54f)
`:Nmread scp://self/.bashrc`
after first time
![image](https://github.com/miversen33/netman.nvim/assets/58662350/625065ab-586a-418f-81be-e9ecbb5eaef2)
after subsequent times
![image](https://github.com/miversen33/netman.nvim/assets/58662350/4d96252d-f074-4430-a078-29337ddec062)

**Comment by Aonodensetsu** [comment] 2024-03-15 14:06
`:Nmread` is equivalent to `.read` but mixing them does not make the other work immediately

nmread -> nmread(works)
.read -> .read(works)
nmread -> .read (does not work) -> nmread/.read (works)

**Comment by miversen33** [comment] 2024-03-15 14:32
That's a whole lot of weirdness going on. I really appreciate the screenshots :)

**Comment by miversen33** [comment] 2024-03-27 22:50
Just a note, I _am_ able to reproduce this issue. So that's fun. I will be creating another branch and seeing what I can figure out

**Comment by miversen33** [comment] 2024-03-28 00:15
Ok so I have figured out what is happening here. The issue you are seeing is related to the addition of async support for providers. This support is relatively robust but it seems there is a bug in how non-async requests work with providers that support async calls. I thought I had that figured out but I guess not. 

For those who are curious, the problem line is [api.lua:1003](https://github.com/miversen33/netman.nvim/blob/main/lua/netman/api.lua#L1003)

This line is a problem because the by including this callback, it informs everything under it that it needs to be asynchronous if possible. That works for 90% of calls as async is the standard/default way of interacting with stuff.

The reason this is falling over is because [we are _not_ providing a callback to read](https://github.com/miversen33/netman.nvim/blob/main/lua/netman/init.lua#L20) but the rest of read is assuming async if possible. Thus the result is basically "lost". That also explains why it "works" after multiple attempts. This is a lucky coincidence due to the api's file read caching system. It sees the file is already downloaded and thus escapes and returns the file contents to open.

I am not sure the best way to handle this. Its likely a 2 pronged approach. I need to fix the actual API logic so it doesn't just assume async at all times. But I should also get `:Nmread` to work asynchronously as well.

**Comment by miversen33** [comment] 2024-04-11 22:51
Another fun bug I have uncovered, multiple `Nmread` calls just overwrite the same buffer. So that's fun :upside_down_face: I suspect that bug has been around for a while and just not noticed.

**Comment by miversen33** [comment] 2024-04-11 23:00
@Aonodensetsu can you try out [Branch 204-bug-nmread-does-not-work](https://github.com/miversen33/netman.nvim/tree/204-bug-nmread-does-not-work) and see if it fixes the issues you outlined?

This doesn't implement async handling for Nmread (something I still want to do) nor does it address the buffer overwriting bug I mentioned above. But I _think_ it fixes the whole "having run the command twice" issue

**Comment by Aonodensetsu** [comment] 2024-04-12 07:33
.ssh/config
```
Host self
    HostName 127.0.0.1
    User <username>
```
not lazy:
term:
`nvim -c 'e ssh://self/.bashrc'` ✅
`nvim -c 'Nmread ssh://self/.bashrc'` ✅
`nvim -c 'lua require"netman".read("ssh://self/.bashrc")'` ✅
nvim file view:
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅
`:lua require'netman'.read('ssh://self/.bashrc')` ✅
neo-tree folder view:
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ❌
`:lua require'netman'.read('ssh://self/.bashrc')` ❌

my lazy config:
term:
`nvim -c 'e ssh://self/.bashrc'` ✅
`nvim -c 'Nmread ssh://self/.bashrc'` ✅
`nvim -c 'lua require"netman".read("ssh://self/.bashrc")'` ✅
nvim file view:
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅❌ does not load file properties
`lua require'netman'.read('ssh://self/.bashrc')` ✅❌ does not load file properties
neo-tree folder view:
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ❌
`:lua require'netman'.read('ssh://self/.bashrc')` ❌

the lazy results also apply after manually loaded with `Lazy load netman.nvim`

**Comment by Aonodensetsu** [comment] 2024-04-12 07:38
from the results, it looks like `e` is fixed, both `Nmread` and `.read` are not fixed in folder view, nor does the plugin load them correctly after `VimStart`
as before, remote folders don't open at all, i will add a bypass to netrw for them unless you plan to add that feature

**Comment by miversen33** [comment] 2024-04-12 12:16
Ya opening folders is going to be a bit of a mess and I am not including that in this branch. That's my next stream of work though after this and getting `Nmread` to play nice with async.

You have a test about "File properties", can I ask what you mean by that?

**Comment by Aonodensetsu** [comment] 2024-04-12 12:39
file type, buffer name eg

**Comment by Aonodensetsu** [comment] 2024-04-12 12:40
tbh i don't really understand why `e` works but not commands directly

**Comment by miversen33** [comment] 2024-04-13 17:59
> The properties not

This doesn't explain anything lol what properties are you expecting to be set? This is likely an oversite on my part as I have absolutely no idea what you are talking about here.

> tbh i don't really understand why e works in folder view but not commands directly, are you sending events correctly? (i'm hooked into BufEnter)

Folder view (in Neo-tree I assume you mean) handles opening files slightly differently than Nmread. This is mostly an artifact of the Neo-tree consumer supporting asynchronous reading of files and native "netman.read" not. Also Neo-tree does some help in creating buffers and opening files which I have to do myself when using "netman.read". Its definitely possible that I am doing something "incorrect" there.

**Comment by Aonodensetsu** [comment] 2024-04-13 19:51
the properties that i listed in that message, file type and buffer name
only the content of the file is put into the buffer

**Comment by miversen33** [comment] 2024-04-13 22:26
Well, that is very strange. I will keep poking. Thank you so much for your help with this :)

**Comment by miversen33** [comment] 2024-04-20 17:53
@Aonodensetsu can you re-pull branch [204-bug-nmread-does-not-work](https://github.com/miversen33/netman.nvim/tree/204-bug-nmread-does-not-work) and see if the issues you listed are still present?

I added some better buffer creation logic (this needed to be done anyway) and fixed the issue with the file name not being set.

I still have not retrofitted Nmread to support async yet and I will _not_ be adding directory support with Nmread in this branch (that is a different set of work I need to do), but I _hope_ to have cleared up the issues you have uncovered here

**Comment by Aonodensetsu** [comment] 2024-04-20 17:57
```lua
Error executing vim.schedule lua callback: Vim:E21: Cannot make changes, 'modifiable' is off
stack traceback:
        [C]: in function 'deletebufline'
        ...local/share/nvim/lazy/netman.nvim/lua/netman/ui/init.lua:288: in function 'render_command_and_clean_buffer'
        ...o/.local/share/nvim/lazy/netman.nvim/lua/netman/init.lua:63: in function 'read'
        /home/ao/.config/nvim/init.lua:706: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by Aonodensetsu** [comment] 2024-04-20 17:58
.read was changed?

**Comment by Aonodensetsu** [comment] 2024-04-20 17:59
ah wait my bad, this is in the lazy code, but i am testing without lazy now

**Comment by miversen33** [comment] 2024-04-20 18:02
That's an odd error, there should never be a point where netman is trying to write to an unmodifiable buffer. I'm sure the process you followed wasn't convoluted but can you provide the logs from `Nmlogs` when you executed `Nmread` there?

And yes, `.read` was slightly modified. `Nmread` is literally just a vim function that passes everything to `.read` so any work being done on `Nmread` will happen in `.read` or further down the call stack

**Comment by Aonodensetsu** [comment] 2024-04-20 18:10
not lazy:
term:
`nvim -c 'e ssh://self/.bashrc'` == `nvim ssh://self/.bashrc` ✅
`nvim -c 'Nmread ssh://self/.bashrc'` ✅❌ shows error 1 but works
`nvim -c 'lua require"netman".read("ssh://self/.bashrc")'` ✅❌ shows error 1 but works
nvim file view (`nvim .bashrc`):
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅
`:lua require'netman'.read('ssh://self/.bashrc')` ✅
neo-tree folder view (`nvim .`):
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅ 
`:lua require'netman'.read('ssh://self/.bashrc')` ✅ 

my lazy config:
term:
`nvim -c 'e ssh://self/.bashrc'` == `nvim ssh://self/.bashrc` ✅
`nvim -c 'Nmread ssh://self/.bashrc'` ✅❌ shows error 2 then 1 but opens
`nvim -c 'lua require"netman".read("ssh://self/.bashrc")'` ✅❌ shows error 1 twice but opens
nvim file view (`nvim .bashrc`):
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅
`lua require'netman'.read('ssh://self/.bashrc')` ✅
neo-tree folder view (`nvim .`):
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅❌shows error 1 but opens
`:lua require'netman'.read('ssh://self/.bashrc')` ✅❌shows error 1 but opens

the lazy results also apply after manually loaded with `Lazy load netman.nvim`

error 1:
```
E5108: Error executing lua Vim:E21: Cannot make changes, 'modifiable' is off
stack traceback:
        [C]: in function 'deletebufline'
        ...local/share/nvim/lazy/netman.nvim/lua/netman/ui/init.lua:288: in function 'render_command_and_clean_buffer'
        ...o/.local/share/nvim/lazy/netman.nvim/lua/netman/init.lua:63: in function 'read'
        [string ":lua"]:1: in main chunk
```
error 2:
```
Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: command line: Vim(lua):E5108: Error executing lua Vim:E21: Cannot make changes, 'modifiable' is off
stack traceback:
        [C]: in function 'deletebufline'
        ...local/share/nvim/lazy/netman.nvim/lua/netman/ui/init.lua:288: in function 'render_command_and_clean_buffer'
        ...o/.local/share/nvim/lazy/netman.nvim/lua/netman/init.lua:63: in function 'read'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>
stack traceback:
        [C]: in function 'cmd'
        .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>
```

**Comment by Aonodensetsu** [comment] 2024-04-20 18:16
https://00t.in/m/netman.log

**Comment by miversen33** [comment] 2024-04-20 18:22
I just pushed up another change, try pulling that down and then trying again.

Also something interesting I am seeing in your logs, it seems that `.read` is being called twice

If you look at line 224, you see a second "Reading ssh://self/.bashrc".

Which of your tests did this log come from?

For reference, here is a log file from my machine when I do the same exact test
[netman2.log](https://github.com/miversen33/netman.nvim/files/15049353/netman2.log)

**Comment by Aonodensetsu** [comment] 2024-04-20 18:31
not lazy:
term:
`nvim -c 'e ssh://self/.bashrc'` == `nvim ssh://self/.bashrc` ✅
`nvim -c 'Nmread ssh://self/.bashrc'` ✅
`nvim -c 'lua require"netman".read("ssh://self/.bashrc")'` ✅
nvim file view (`nvim .bashrc`):
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅
`:lua require'netman'.read('ssh://self/.bashrc')` ✅
neo-tree folder view (`nvim .`):
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅ 
`:lua require'netman'.read('ssh://self/.bashrc')` ✅ 

my lazy config:
term:
`nvim -c 'e ssh://self/.bashrc'` == `nvim ssh://self/.bashrc` ✅
`nvim -c 'Nmread ssh://self/.bashrc'` ✅
`nvim -c 'lua require"netman".read("ssh://self/.bashrc")'` ✅
nvim file view (`nvim .bashrc`):
`:e ssh://self/.bashrc` ✅
`:Nmread ssh://self/.bashrc` ✅
`lua require'netman'.read('ssh://self/.bashrc')` ✅
neo-tree folder view (`nvim .`):
`:e ssh://self/.bashrc` ✅❌loads content twice
`:Nmread ssh://self/.bashrc` ✅❌loads content twice
`:lua require'netman'.read('ssh://self/.bashrc')` ✅❌loads content twice

**Comment by Aonodensetsu** [comment] 2024-04-20 18:31
yeah i have no idea why it gets called twice

**Comment by Aonodensetsu** [comment] 2024-04-20 18:33
this is my lazy load code in netman's (neo-tree's actually) init
```lua
vim.api.nvim_create_autocmd('BufEnter', {
  group    = vim.api.nvim_create_augroup('RemoteFileInit', {clear = true}),
  callback = function()
    local f = vim.fn.expand('%:p')
    -- TODO: netman #204
    local active = false
    for _, v in ipairs{'sftp', 'ssh', 'scp', 'docker'} do
      local p = v .. '://'
      if string.sub(f, 1, #p) == p then
        vim.defer_fn(function()
          require'netman'.read(f)
        end, 0)
        active = true
        break
      end
    end
    if active then
      vim.api.nvim_clear_autocmds{group = 'RemoteFileInit'}
    end
  end
})
```

**Comment by Aonodensetsu** [comment] 2024-04-20 18:44
if i run the command again to reopen the file it loads once and works

**Comment by miversen33** [comment] 2024-04-20 21:20
So interestingly, I am noticing that when I execute `Nmread` after opening a directory with `nvim .` (which loads up neo-tree), Neovim closes instead of doing anything.

You are not seeing that behavior which now has me wondering what is different between our 2 setups. Can you provide me a minimal replication config?

**Comment by Aonodensetsu** [comment] 2024-04-21 16:43
i am unable to replicate nvim closing

**Comment by miversen33** [comment] 2024-04-21 16:50
It's likely my neotree configuration. What would be most beneficial to me is to isolate your issue in a minimal reproducible configuration. Can you provide me one with just the bare minimum needed to recreate your issue you're seeing when you open up a directory and then execute `Nmread`?

**Comment by Aonodensetsu** [comment] 2024-04-21 16:52
my lazy config is somehow the issue but i have no idea how since it just calls .read, i'm assuming events are fired in a weird order and the call interrupts an already opening copy of Nmread

**Comment by Aonodensetsu** [comment] 2024-04-21 17:05
switching from `BufEnter` to `BufNewFile` fixes the previous issues but makes the `-c` commands load content twice

**Comment by Aonodensetsu** [comment] 2024-04-21 17:43
okay so i think there still is some issue with `Nmread` that is not there with .read

**Comment by Aonodensetsu** [comment] 2024-04-21 17:47
when netman is set to lazy, `-c .read` works fine, but `-c Nm` not

**Comment by miversen33** [comment] 2024-04-21 17:50
Ya that makes sense. If you are lazy loading Netman, it can't define the vim commands (since you are never loading Netman). Thus, `:Nmread` literally doesn't exist and therefore nothing happens when you call it.

There is really no reason to lazy load Netman.

**Comment by Aonodensetsu** [comment] 2024-04-21 17:52
lazy.nvim can be set up to catch commands that will exist after a plugin loads, and the plugin does load, just doesn't load correctly

**Comment by Aonodensetsu** [comment] 2024-04-21 17:53
netman is currently not loaded, lazy.nvim is creating fake commands that will load the plugin then run the real one:
![image](https://github.com/miversen33/netman.nvim/assets/58662350/6afe9632-866d-4b2e-855c-895b527f58ef)

**Comment by miversen33** [comment] 2024-04-21 18:22
> it isn't that big of a deal to not lazyload netman, but it would be nice if it was possible to do so

While I can respect your specific usecase, lazyloading Netman is not something I will be supporting. Netman is a framework and part of its framework is doing exactly what you have coded in your lazy configuration.

If you remove lazy loading of netman, can you confirm that things work 'as expected'? in this new branch?

**Comment by Aonodensetsu** [comment] 2024-04-21 18:39
after a clean install i'm having the same issue without my lazy load code with both `-c` options (`e` works)

**Comment by miversen33** [comment] 2024-04-21 18:41
Please provide me a minimal reproducible configuration so I can replicate and test on my local system.

**Comment by Aonodensetsu** [comment] 2024-04-21 18:51
'doing the same thing and expecting different results' is called crazy, but that's what i'm experiencing, literally every time i do a clean reinstall something else happens lol

**Comment by Aonodensetsu** [comment] 2024-04-21 18:54
now it doesn't even work in file view 😢

**Comment by miversen33** [comment] 2024-04-21 19:16
That makes sense, the code expects that if there is a buffer that already exists with the same URI path as the file being opened, it can just reuse that buffer. The bug here would be that I do not clear the buffer out first. I should probably address that, look for an update to the branch sometime this afternoon.

I will again ask that you provide me a minimal configuration to recreate the problems you are seeing. Some of them I am able to recreate myself but I do not have the time nor energy to keep trying to blindly chase down issues that are being reported.

I am certain the issues you are seeing exist, but some of them I just can't replicate

**Comment by Aonodensetsu** [comment] 2024-04-21 19:20
let's start with this one cause it might fix everything, if the buffer gets cleaned before write it wouldn't matter if the command opens it twice

**Comment by miversen33** [comment] 2024-04-21 19:34
I just pushed up a fix for that

**Comment by Aonodensetsu** [comment] 2024-04-21 20:06
yeah this just fixed everything including the lazy config

**Comment by miversen33** [comment] 2024-04-21 20:07
Weird. Can you do your testing quick to verify "_all is well_"?

**Comment by Aonodensetsu** [comment] 2024-04-21 20:07
i did

**Comment by miversen33** [comment] 2024-04-21 20:07
So if I were to merge this into main, would you consider this issue (sans async) resolved?

**Comment by Aonodensetsu** [comment] 2024-04-21 20:07
yup

**Comment by miversen33** [comment] 2024-04-21 20:09
Migrate to Main, this has been resolved and that branch was merged and closed :)

**Closed** 2024-04-21 20:08 UTC
Labels: bug, documentation, question, Core

**Comment by Aonodensetsu** [comment] 2024-04-21 20:14
bueno, main works too, thanks
